---
title: "xlsxtable"
author: "Eben Pendleton"
date: "2021-02-15"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{xlsxtable}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Introduction
Welcome to an overview and examples for Integral's Excel table function. The
first step is to load the library
```{r setup}
# load the library
library(integral)
```
## xlsxtable
An example dataframe and table is below.
```{r}
## Example code
table.num <- 1
#Create title
title <- paste("Table A-",table.num, "Example Table",sep="")

#Select style (LL for letter-landscape, LP for letter-portrait, and LD for Ledger (11x17))
style <- "LD"

#Select number of identifier columns (non-numeric columns such as "chemical name") that should be left justified (instead of centered)
leftjust <- 2

int_vec <- c('1', '2', '3')
char_vec <- c("a", "b", "c")
bool_vec <- c(TRUE, TRUE, FALSE)
d <- data.frame(int_vec, char_vec, bool_vec)

fpath <- "outtable.xlsx"
sheet <- "Sheet1"
title <- "Example Table"
author <- "Eben Pendleton"
# This returns the Excel out file path if successful.
outpath <- xlsxtable(sheet, d, title, author, fpath = fpath)
```
Here's an example using a workbook. This is to be used when adding
multiple tables
```{r}
fpath <- "outtable.xlsx"
sheet <- "Sheet2"
title <- "Example Table"
author <- "Eben Pendleton"

# create workbook
wb <- openxlsx::createWorkbook()

# This returns the Excel workbook object if successful.
wb <- xlsxtable(sheet, d, title, author, wb = wb)

# Save the workbook
openxlsx::saveWorkbook(wb, file = fpath, overwrite = TRUE)
```


